version: "3.6"

services:
  postgresql:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: aqa_shop

volumes:
  postgresql:
