version: "3.6"

services:
  mysql:
    image: mysql:5
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: aqa_shop

volumes:
  mysql:
